# Generated by Django 4.2.27 on 2026-01-10 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('academic_admin', 'Academic Admin'), ('super_admin', 'Super Admin')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AcademicAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Academic Admins',
                'db_table': 'academic_admins',
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=100)),
                ('academic_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_sessions',
            },
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('program_interest', models.CharField(blank=True, max_length=200)),
                ('inquiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('event', 'Event')], max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicadmin')),
            ],
            options={
                'db_table': 'admission_inquiries',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_elective', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('syllabus', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('schedule', models.JSONField(default=dict)),
                ('max_students', models.IntegerField(default=50)),
                ('current_enrollment', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academic.course')),
            ],
            options={
                'db_table': 'course_offerings',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('office_location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('practical', 'Practical')], max_length=50)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('syllabus_portion', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academic.courseoffering')),
            ],
            options={
                'db_table': 'examinations',
                'ordering': ['-exam_id'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('facilities', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'exam_rooms',
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_number', models.CharField(blank=True, max_length=20)),
                ('office_hours', models.TextField(blank=True)),
                ('hire_date', models.DateField()),
                ('qualification', models.TextField(blank=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='academic.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=200)),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('duration_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_credits_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('program_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('doctoral', 'Doctoral')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.department')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_reg_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500)),
                ('enrollment_date', models.DateField()),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', max_length=50)),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_date', models.DateField(default=django.utils.timezone.now)),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('file_url', models.URLField(max_length=500)),
                ('is_official', models.BooleanField(default=True)),
                ('verification_hash', models.CharField(blank=True, max_length=100)),
                ('issued_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_transcripts', to='academic.academicadmin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='academic.student')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='ZoomClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('schedule_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('join_link', models.TextField()),
                ('recording_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], default='zoom', max_length=50)),
                ('start_url', models.TextField(blank=True)),
                ('created_by_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_zoom_classes', to='academic.facultymember')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_classes', to='academic.courseoffering')),
            ],
            options={
                'db_table': 'zoom_classes',
            },
        ),
        migrations.CreateModel(
            name='TranscriptDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester_name', models.CharField(max_length=100)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='academic.transcript')),
            ],
            options={
                'verbose_name_plural': 'Transcript Details',
                'db_table': 'transcript_details',
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='study_materials/%Y/%m/')),
                ('file_type', models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('assignment', 'Assignment'), ('syllabus', 'Syllabus'), ('book', 'Book'), ('video_lecture', 'Video Lecture'), ('tutorial', 'Tutorial'), ('presentation', 'Presentation'), ('code', 'Code/Project'), ('dataset', 'Dataset'), ('other', 'Other')], default='lecture_notes', max_length=50)),
                ('file_size', models.BigIntegerField(default=0)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('enrolled_only', 'Enrolled Students Only')], default='enrolled_only', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='academic.courseoffering')),
                ('uploaded_by_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='academic.facultymember')),
            ],
            options={
                'db_table': 'study_materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_number', models.IntegerField()),
                ('semester_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enrollment_start_date', models.DateField()),
                ('enrollment_end_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicsession')),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResultPublication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('published_to_students_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_results', to='academic.academicadmin')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='academic.semester')),
            ],
            options={
                'db_table': 'result_publications',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('faculty', 'Faculty'), ('specific_department', 'Specific Department')], default='all', max_length=50)),
                ('is_pinned', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department')),
                ('posted_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(max_length=50)),
                ('assessment_name', models.CharField(max_length=200)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('graded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_finalized', models.BooleanField(default=False)),
                ('graded_by_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_assessments', to='academic.facultymember')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.student')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_faculty', to='academic.facultymember')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('seating_plan', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.examination')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilated_exams', to='academic.facultymember')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academic.examroom')),
            ],
            options={
                'db_table': 'exam_schedules',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dropped', 'Dropped'), ('frozen', 'Frozen')], default='confirmed', max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicadmin')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.student')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academic.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_department', to='academic.facultymember'),
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('prerequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisites', to='academic.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='academic.course')),
            ],
            options={
                'db_table': 'course_prerequisites',
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academic.facultymember'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academic.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.department'),
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_classes', models.IntegerField(default=0)),
                ('attended_classes', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateField()),
                ('warning_sent', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='academic.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='academic.student')),
            ],
            options={
                'db_table': 'attendance_summaries',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('qr_token', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to='academic.facultymember')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.student')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('applied_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('documents', models.JSONField(default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('accepted_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicadmin')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='academic.admissioninquiry')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='academic.program')),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('admit_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('seat_number', models.CharField(blank=True, max_length=20)),
                ('qr_code_data', models.TextField(blank=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('eligibility_status', models.CharField(default='eligible', max_length=50)),
                ('verification_log', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='academic.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='academic.student')),
            ],
            options={
                'db_table': 'admit_cards',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='academicadmin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='academic.department'),
        ),
        migrations.AddField(
            model_name='academicadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='registered', max_length=50)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='academic.enrollment')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='academic.student')),
            ],
            options={
                'db_table': 'student_course_registrations',
                'indexes': [models.Index(fields=['student_id'], name='student_cou_student_35c061_idx')],
                'unique_together': {('student', 'offering')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user_id'], name='students_user_id_b061ff_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program_id'], name='students_program_cb6333_idx'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(('semester_number__gte', 1), ('semester_number__lte', 3)), name='check_semester_number_range'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['target_audience', 'post_date'], name='notices_target__ea22f6_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student_id', 'offering_id'], name='grades_student_3c6bef_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student_id', 'semester_id'], name='enrollments_student_e8ccec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course', 'prerequisite_course')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student', 'offering')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student_id', 'offering_id', 'attendance_date'], name='attendance_student_439da5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'offering', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='admitcard',
            unique_together={('student', 'exam')},
        ),
    ]
