# Generated by Django 4.2.27 on 2025-12-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
