# Generated by Django 4.2.27 on 2026-01-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admitcard',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-exam_id']},
        ),
        migrations.AlterModelOptions(
            name='examroom',
            options={'ordering': ['building', 'room_number']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date']},
        ),
    ]
