# Generated by Django 4.2.27 on 2026-01-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_add_studymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='academic.facultymember'),
        ),
    ]
