# Generated by Django 4.2.27 on 2026-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_studymaterial_uploaded_by_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
